// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DNSPropagationChecker
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("recordType")]
        public string RecordType { get; set; }

        [JsonProperty("propagationComplete")]
        public bool PropagationComplete { get; set; }

        [JsonProperty("serversChecked")]
        public long ServersChecked { get; set; }

        [JsonProperty("serversResponded")]
        public long ServersResponded { get; set; }

        [JsonProperty("uniqueResponses")]
        public long UniqueResponses { get; set; }

        [JsonProperty("results")]
        public Result[] Results { get; set; }
    }

    public partial class Result
    {
        [JsonProperty("server")]
        public string Server { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("ip")]
        public string Ip { get; set; }

        [JsonProperty("success")]
        public bool Success { get; set; }

        [JsonProperty("records")]
        public Record[] Records { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("responseTime")]
        public long ResponseTime { get; set; }
    }

    public enum Record { The1422508046 };
}
